### ISSUE TITLE
[BUG] Dark Mode Switch

### ISSUE THREAD

**Issue by himanshu1221** [girlscript/gssoc-website-new#106]
When we switch to dark mode it is not switching smoothly 

https://github.com/girlscript/gssoc-website-new/assets/32031706/6153b835-3b53-448f-bb71-00f334bb4168

**Comment by himanshu1221** [comment]
> @himanshu1221 which browser are you using?
> 
> It worked fine on my Chrome, Arc and Firefox browsers.

Chrome

**Comment by Suvraneel** [comment]
@himanshu1221 I suppose its due to low Internet connectivity speed. I tried that normally, couldn't reproduce. Then I turned on throttle and then it happened. Basically the assets are taking time to load up.

Anyway, if you've any suggestions to improve it and wanna work on it, feel free to tag me there.
