### ISSUE TITLE
Improve project filter system

### ISSUE THREAD

**Issue by Nkmeoo7** [girlscript/gssoc-website-new#219]
# project filtration

In the home page ,If someone click on tailwind css there is no project showing
![Screenshot 2024-05-11 122822](https://github.com/girlscript/gssoc-website-new/assets/130870802/aa87b2d3-44b6-4209-a8e0-8cad75679966)

***expected behaviour***

![Screenshot 2024-05-11 122855](https://github.com/girlscript/gssoc-website-new/assets/130870802/886dd1c7-def9-4708-b6db-f9d70ca55f8e)

**Comment by iamhvsharma** [comment]
I have solved the issue, Kindly review it please and merge it. 

@sanjay-kv

**Comment by sanjay-kv** [comment]
Hi @iamhvsharma , Kindly notice, only work on issue if its assigned to you. You can see this is assigned to @Nkmeoo7 unless he keeps the issue stale for 5 days, I will pass to next one based on first come first serve basis. I hope you get this. Sorry about that. Its the rule we made to follow inclusive contribution.

**Comment by iamhvsharma** [comment]
I think this rule is not good because if someone has done it before then it should be given priority as there should be a competition among contributors to solve the issue before someone else. I think this way will increase the productivity and competition among the contributors. 

Also, how can I make sure that @Nkmeoo7 will not see my PR to solve the issue? Should I delete my PR?

**Comment by sanjay-kv** [comment]
I hope you guys know this repo is not listed in leaderboard.

**Comment by iamhvsharma** [comment]
Yes I know!

I am doing it just for making the GirlScript a better website.
